feat:界面优化
CLDXiang/huiyou.js pull request #16
Opened 2020-11-14 15:00 UTC by carolthepooh

2020-11-15 10:58 UTC, CLDXiang requested changes
除了 comments 中的问题外还有：

- logo 图片文件是损坏的
- 浏览器窗口较小时布局会崩掉，可以思考一下如何调整

2020-11-15 10:58 UTC, CLDXiang commented on src/app/components/PushRecordItem.vue
> +    <div :class="'content'+ (isLast?' last':'')">
这里用这个写法：

```vue
<div class="content" :class="{ last: isLast }">
```

参考 [Vue 官方文档](https://v3.cn.vuejs.org/guide/class-and-style.html#%E7%BB%91%E5%AE%9A-html-class)

2020-11-15 10:58 UTC, CLDXiang commented on src/app/views/PushRecords.vue
> +      if (records.length > 0) {
这样一块逻辑区最好加一行注释简要写一下是做什么的，另外这里的 for 循环其实可以用数组的 `map` 或 `forEach` 方法实现（这是 ES6 推荐的做法）

2020-11-15 12:48 UTC, carolthepooh commented on src/app/views/PushRecords.vue
> +      if (records.length > 0) {
这里用for更方便吧，foreach还要判断index是不是0，而且还不方便取i-1条数据

2020-11-15 13:52 UTC, carolthepooh commented on src/app/views/PushRecords.vue
> +      if (records.length > 0) {
这里的话for更方便吧，foreach还要判断index是不是0

2020-11-23 02:36 UTC, CLDXiang approved these changes
LGTM

2020-11-23 02:37 UTC, merged