feat:push records
CLDXiang/huiyou.js pull request #6
Opened 2020-10-25 05:18 UTC by carolthepooh

新增推送记录展示页面（暂未对接后端数据）

2020-10-25 14:51 UTC, carolthepooh reviewed
对接了后端数据，实现跳题跳转

2020-10-26 08:34 UTC, CLDXiang requested changes
rest LGTM，提交前运行一下 `yarn lint`，本地 vscode 装一下 eslint 插件，用本地（node_modules）里的配置，代码中出现警告不要忽视

2020-10-26 08:34 UTC, CLDXiang commented on package.json
> +    "element-ui": "^2.13.2",
element ui 没有用到可以去掉这一行

2020-10-26 08:34 UTC, CLDXiang commented on src/apis/index.ts
> +export interface Record {
Record 是 TS 的保留关键字，换一个命名吧

2020-10-26 08:34 UTC, CLDXiang commented on src/apis/index.ts
> +    description: string;
interface 中尽量写一下字段注释：

```ts
interface Xxx {
  /** 用户 Id */
  uid: string;
  /** up 主 */
  author: string;
  ...
}
```

2020-10-26 08:34 UTC, CLDXiang commented on src/app/App.vue
> +import PushRecords from './pages/PushRecords.vue';
目录里 `pages` 用 `views` 吧，遵循 vue 官方推荐的命名

2020-10-26 08:34 UTC, CLDXiang commented on src/app/components/PushRecordItem.vue
> +        <span style="margin-left:100px">作者:{{ author }}</span>
这里行内样式没有空格，另外除非必要，尽量把样式都写在 style 里，分开会提高维护成本

2020-10-26 08:34 UTC, CLDXiang commented on src/app/components/PushRecordItem.vue
> +    bv: String,
这里会报 eslint warning，用完整写法：

```
img: { type: String, required: true }
```

或

```
img: { type: string, default: xxx }
```

2020-10-26 08:34 UTC, CLDXiang commented on src/app/components/PushRecordItem.vue
> +          cursor: pointer;
缩进歪了

2020-10-26 08:34 UTC, CLDXiang commented on src/app/pages/PushRecords.vue
> +        :key="item.uid"
uid 对于 records 来说应该不是唯一的吧？key 应当用循环项中唯一的值，比如这里 bv 大概率不会重复，那就该用 bv

2020-10-26 08:34 UTC, CLDXiang commented on src/app/pages/PushRecords.vue
> +import httpClient from '@/apis/index';
index 可以不写 -> `import httpClient from '@/apis';`

2020-10-26 08:34 UTC, CLDXiang commented on src/app/pages/PushRecords.vue
> +  name: 'PushRecords',
name 在单文件组件里不是必要的

2020-10-26 08:34 UTC, CLDXiang commented on src/app/pages/PushRecords.vue
> +      records: {},
这里最好给出类型定义，records: {} as Xxx（某个 TS 定义）

2020-10-26 08:34 UTC, CLDXiang commented on src/app/pages/PushRecords.vue
> +      console.log(data);
不要留 console.log，如果确实需要输出可以用 `@/utils/logger`

2020-10-26 08:34 UTC, CLDXiang commented on src/app/pages/PushRecords.vue
> +    .header {
缩进用 2 格

2020-10-26 08:34 UTC, CLDXiang commented on src/main.ts
> +import 'ant-design-vue/dist/antd.css';
用按需加载，这样全部加载会有比较大的网络负担，比如

```ts
import { Button, Timeline } from 'ant-design-vue';

const app = createApp(App);

app.use(Button).use(Timeline);

app.mount('#app');
```

2020-10-26 08:35 UTC, CLDXiang commented on package.json
> +    "element-ui": "^2.13.2",
删除用 `yarn remove`，否则需要手动清理 `yarn.lock` 文件中相应内容

2020-10-27 08:07 UTC, CLDXiang approved these changes
LGTM

2020-10-27 08:07 UTC, CLDXiang commented on src/apis/index.ts
> +  uid: string;
uid 注释漏了，不过问题不大

2020-10-27 08:07 UTC, merged