content script：popup窗口基础功能实现
CLDXiang/huiyou.js pull request #7
Opened 2020-10-29 02:51 UTC by Stephyuka

popup页面脚本实现：
- 与background脚本可以通信
- 支持窗口popup
- 支持计时消失
- 显示推荐视频缩略图
- 显示推荐视频标题
- 点击视频标题可进入推荐视频

对插件ui的优化：
- 添加了插件图标

2020-10-29 04:27 UTC, CLDXiang requested changes
先改一些细节，过一会儿再 review 核心逻辑

2020-10-29 04:27 UTC, CLDXiang commented on package.json
> +    "antd": "^4.7.3",
？为什么引入了 React 的 Ant Design？`yarn remove antd` 一下

2020-10-29 04:27 UTC, CLDXiang commented on public/manifest.json
> +    "128":"img/tag.png"
只给一个尺寸没问题吗？似乎官方示例里都给了 16 32 48 128 四种尺寸，在不同场景下显示

2020-10-29 04:27 UTC, CLDXiang commented on public/manifest.json
> +    "default_icon":"img/tag-browser.png"
同上

2020-10-29 04:27 UTC, CLDXiang commented on public/manifest.json
> +    "default_title": "huiyou",
这里咱要不要改中文？

2020-10-29 04:27 UTC, CLDXiang commented on src/background/config.ts
> +  PLAYED_TIME_PROPORTION_LOWER_LIMIT: 1 / 3, // origin: 1/3
多余的注释可以删掉

2020-10-29 04:27 UTC, CLDXiang commented on src/background/config.ts
> +  VIDEO_COUNT_LOWER_LIMIT: 5, // origin： 5
同上

2020-10-29 04:27 UTC, CLDXiang commented on src/background/messageCallback.ts
> +  logger.info('message handler');
调试用的信息可以不用 commit 进来

2020-10-29 04:27 UTC, CLDXiang commented on src/popup/config.ts
> +export const SHOW_VIDEO = freeze({
这个可以删掉，应该是由 background 维护的

2020-10-29 04:27 UTC, CLDXiang commented on src/popup/config.ts
> +export const TIMEKEEPING = freeze({
这个可以直接用 background 那边的，可以先不改，把这个变量提到顶层后两边用同一个

2020-10-29 04:27 UTC, CLDXiang commented on src/popup/main.ts
> +// chrome.runtime.onMessage.addListener(handleMessage);
无用代码可以删去

2020-10-29 04:27 UTC, CLDXiang commented on src/utils/logger.ts
> +      logger.info(...args);
？这里为啥要这样改

2020-10-29 04:42 UTC, Stephyuka commented on public/manifest.json
> +    "128":"img/tag.png"
只给一个尺寸是可以自动转换的 当然我都加上吧

2020-10-29 04:43 UTC, Stephyuka commented on src/utils/logger.ts
> +      logger.info(...args);
find & replace的锅 我改掉

2020-11-04 12:32 UTC, CLDXiang requested changes
多是小问题，有大问题的只有切窗口时间同步那里的计时器设置

2020-11-04 12:32 UTC, CLDXiang commented on src/background/config.ts
> +  PLAYED_TIME_PROPORTION_LOWER_LIMIT: 0,
调试用的数据不要 push 上来，下同

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/main.ts
> +export const play = {
不用 `export`

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/main.ts
> +  flag: 0,
这个 `flag` 可以语义化一点，要么加个注释

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/main.ts
> +export const play = {
这个 play 里面的两个值到底是做什么用的？我貌似没看到调用的地方？

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/popup.less
> +  transition: color .3s;
这里的 `transition` 属性本来就是下面的四个属性的缩写，可以直接都写在 `transition` 里

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/popup.less
> +  text-overflow:ellipsis;
随手缩进一下，`:` 后面加空格

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/popup.less
> +  margin-left: auto;
`margin-left: auto` 和 `margin-right: auto` 可以缩写为 `margin: 0 auto`

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/showVideo.ts
> +  setTimeout(() => {
窗口失焦的时候应该取消这个计时器？

2020-11-04 12:32 UTC, CLDXiang commented on src/popup/showVideo.ts
> +    expiration = time;
这里应该需要启动计时器吧？

2020-11-10 08:27 UTC, zhangzhengyi1024 commented
@Stephyuka 很多接口都有较大的变化，需要重新对接

2020-11-23 05:39 UTC, Stephyuka commented
@CLDXiang 求review

2020-11-23 11:50 UTC, CLDXiang requested changes
rest LGTM

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/popup.less
> +  transition: color .3s transition-property color transition-duration 0.3s transition-timing-function ease transition-delay 0s;
这写得不对，参考 mdn 文档 transition 属性的写法

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/showVideo.ts
> +import { getVideoInfo } from '@/apis/bilibili';
业务代码中不该直接调用 `@/apis` 的接口方法，应该在模块内封装一层后进行调用

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/main.ts
> +    imgBox.style.backgroundImage = `url(${docUrl})`;
utils 应该有写 addStyle 方法，可以用对象的形式写 css 属性，没必要每一个属性都用 `xxx.style.yyy = zzz`

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/showVideo.ts
>        videoImg.style.backgroundImage = `url(${video.pic})`;
同上，可以用 `addStyle`

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/timeKeeper.ts
> +function offVideo(popupBox: HTMLDivElement) {
这个文件内的每个函数最好写一下头注，如

```ts
/** 隐藏 popup */
funciton offViedo(...
```

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/timeKeeper.ts
> +let expiration: number | null = null;
这个 `expiration` 好像没用上？事实上应该使用它才对

2020-11-23 11:50 UTC, CLDXiang commented on src/popup/timeKeeper.ts
> +export function startTimekeeping(popupBox: HTMLDivElement) {
这个函数，以及下面那个函数，实现有些奇怪，应当利用 expiration 保证页面中仅有一个计时器在倒计时，现在这样每一次切换 tab 就会新增一个计时器，虽然看起来应该会达到想要的效果，但是内存泄露应该是我们需要避免的

2020-11-26 01:12 UTC, CLDXiang requested changes

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/bilibiliApi.ts
> +      img_y_size: rawData.img_y_size,
这里的 key 可以自己转成 camelCase，不然在外部还要 eslint-disable

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/popup.less
> +  transition-delay: 0s;
这里怎么又加出来了？这五行可以直接写 `transition: color .3s ease`

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/showVideo.ts
> +  addStyle(videoImg, 'backgroundImage: ' as CSSProperties);
addStyle 不该这样用，这不是比直接写还麻烦了吗？

```ts
addStyle(videoImg, {
  backgroundImage: '',
})
```

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/showVideo.ts
> +  addStyle(popupBox, 'visibility: hidden' as CSSProperties);
同上

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/showVideo.ts
> +      addStyle(popupBox, 'visibility: visible' as CSSProperties);
同上

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/showVideo.ts
> +      addStyle(videoImg, 'backgroundSize: 100% 100%' as CSSProperties);
```ts
addStyle(videoImg, {
  backgroundImage: `url(${video.pic}`,
  backgroundRepeat: 'no-repeat',
  backgroundSize: '100% 100%',
})
```

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/timeKeeper.ts
> +    addStyle(popupBox, 'visibility: hidden' as CSSProperties);
同上，另外仅有一个样式要改的时候其实不一定要用 addStyle，这个工具函数本来就是为了避免反复写 xxx.style.yyy = zzz 的，仅有一行的时候就没必要用了

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/timeKeeper.ts
> +    addStyle(popupBox, 'visibility: visible' as CSSProperties);
同上

2020-11-26 01:12 UTC, CLDXiang commented on src/popup/videoShot.ts
> +    addStyle(videoPic, `backgroundPositionY: ${10 - 84.5 * (idx % videoInfo.img_x_len)}$px` as CSSProperties);
同上

2020-11-26 14:52 UTC, Stephyuka commented on src/popup/popup.less
> +  transition-delay: 0s;
我看了mdn文档 是分开写的

2020-11-26 15:04 UTC, Stephyuka commented on src/popup/timeKeeper.ts
> +    addStyle(popupBox, 'visibility: hidden' as CSSProperties);
为了格式统一还是用吧？

2020-11-26 15:06 UTC, Stephyuka commented on src/popup/bilibiliApi.ts
> +      img_y_size: rawData.img_y_size,
但是b站返回的json里面这个字段就是非camelCase 改掉不会有问题吗

2020-11-26 20:57 UTC, CLDXiang commented on src/popup/popup.less
> +  transition-delay: 0s;
> 我看了mdn文档 是分开写的

https://developer.mozilla.org/zh-CN/docs/Web/CSS/transition

2020-11-26 20:59 UTC, CLDXiang commented on src/popup/bilibiliApi.ts
> +      img_y_size: rawData.img_y_size,
> 但是b站返回的json里面这个字段就是非camelCase 改掉不会有问题吗

这里就是做原始接口和业务代码的转换呀

```ts
imgXLen: rawData.img_x_len,
```

这样在业务代码里就不存在 camelCase 的问题了

2020-11-26 21:02 UTC, CLDXiang requested changes
有几处 addStyle 仍是错误的用法

2020-11-26 21:02 UTC, CLDXiang commented on .gitignore
> +src/background/backend.ts
这里是啥情况？

2020-11-26 21:02 UTC, CLDXiang commented on src/popup/timeKeeper.ts
> +    addStyle(popupBox, 'visibility: hidden' as CSSProperties);
都行

2020-11-26 21:05 UTC, CLDXiang commented on src/popup/bilibiliApi.ts
> +      img_y_size: rawData.img_y_size,
而且这里有些奇怪，为啥 `...rawData` 后又每一个字段都又重复赋了一遍值？

2020-11-29 05:20 UTC, CLDXiang approved these changes
LGTM

2020-11-29 05:21 UTC, merged